name: Deploy to GitHub Pages

on:
  push:
    branches: ["master"]  # Ou "main" selon votre branche

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4  # Version mise à jour

      - name: Build static site
        run: |
          mkdir -p public
          [ -f index.html ] && cp index.html public/ || true
          [ -f style.css ] && cp style.css public/ || true
          [ -f script.js ] && cp script.js public/ || true

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3  # Nouvelle version
        with:
          path: 'public/'

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4  # Version mise à jour